# Generated by Django 5.2.13 on 2026-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_category_thumbnail_category_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
