# Generated by Django 5.2.13 on 2026-04-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_category_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
