# Generated by Django 5.2.13 on 2026-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_thumbnail_url_category_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='url',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
