# Generated by Django 5.2.13 on 2026-04-27 17:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_productmedia_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
