# Generated by Django 5.2.13 on 2026-05-03 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cogs', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bei', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mahali', models.CharField(max_length=100)),
                ('aina', models.CharField(choices=[('ndani', 'Ndani'), ('mkoa', 'Mkoa')], max_length=100)),
                ('idadi', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('makusanyo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('matumizi', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('canceled', 'Canceled')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stock')),
            ],
        ),
    ]
