# Generated by Django 5.2.12 on 2026-04-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='bidhaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stock'),
        ),
    ]
